name: fluttermvvmtemplate
description: A Flutter template project for everyone.

publish_to: none 

version: 0.0.9

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  provider: ^6.0.3

  # network
  # dio: ^4.0.0-prev3
  vexana: ^3.0.1

  # database
  shared_preferences: ^2.0.5

  # language
  easy_localization: ^3.0.0

  # firebase
  firebase_core: ^1.23.0
  firebase_analytics: any
  
  # core utilities
  kartal: ^2.1.0
  logger: ^1.0.0
  webview_flutter: ^3.0.4

  # ui utilities
  animations: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^1.1.5
  lottie: ^1.4.2
  shimmer: ^2.0.0-nullsafety.0

  architecture_theme:
    git:  https://github.com/VB10/architecture_theme.git
  architecture_widgets:
    path: module/architecture_widgets
  all_of_template:
    path: module/all_of_template
  firebase_app_installations: ^0.1.1+8
  flutterfire: ^0.0.1
  fireflutter: ^0.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  json_annotation: ^4.7.0
  json_serializable: ^6.4.0
  mobx_codegen: ^2.0.7+3
  mockito: ^5.3.2
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - asset/lang/
    - asset/svg/
    - asset/image/
    - asset/lottie/